import type { Metadata } from 'next'
//import { Inter } from 'next/font/google'
import './globals.css'

//const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Web Tutorial',
  description: 'Generated by Minha Lee',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html>
      <body>
      <h1><a href="/">WEB</a></h1>
      <ol>
        <li><a href="/read/1">html</a></li>
        <li><a href="/read/1">css</a></li>
        <li><a href="/read/1">JavaScript</a></li>
      </ol>
      {children}
      <ul>
          <li><a href="/create">Create</a></li>
          <li><a href="/update/1">Update</a></li>
          <li><input type="button" value="delete"/></li>
      </ul>
      </body>
    </html>
  )
}
